IBX-6315: Edit/Preview embeded items
ibexa/fieldtype-richtext pull request #123
Opened 2023-08-23 08:22 UTC by lucasOsti

| Question           | Answer
| ------------------ | ------------------
| **JIRA issue**     | [IBX-6315](https://issues.ibexa.co/browse/IBX-6315)
| **Bug/Improvement**| yes/no
| **New feature**    | yes
| **Target version** | 4.6
| **BC breaks**      | no
| **Tests pass**     | no
| **Doc needed**     | no

**TODO**:
- [ ] Implement feature / fix a bug.
- [ ] Implement tests.
- [ ] Fix new code according to Coding Standards (`$ composer fix-cs`).
- [ ] Ask for Code Review.

2023-09-01 13:57 UTC, GrabowskiM requested changes

2023-09-01 13:57 UTC, GrabowskiM commented on src/bundle/Resources/public/js/CKEditor/embed/content-inline/embed-inline-editing.js
> +                data-ibexa-update-source-data-path="Content.Name">${title}</span>
```suggestion
                data-ibexa-update-source-data-path="Content.Name"
            >
                ${title}
            </span>
```

2023-09-01 13:57 UTC, GrabowskiM commented on src/bundle/Resources/public/js/CKEditor/embed/content-inline/embed-inline-ui.js
> +            languageCodes: items[0].ContentInfo.Content.CurrentVersion.Version.VersionInfo.VersionTranslationInfo.Language.map(
maybe put `items[0].ContentInfo.Content` into variable? it's also used in line 18 and 19, thanks to this variable you'll also shorten this line

2023-09-01 13:57 UTC, GrabowskiM commented on src/bundle/Resources/public/js/CKEditor/embed/content/embed-editing.js
> +                data-ibexa-update-source-data-path="Content.Name">${title}</span>
```suggestion
                data-ibexa-update-source-data-path="Content.Name"
            >
                ${title}
            </span>
```

2023-09-01 13:57 UTC, GrabowskiM commented on src/bundle/Resources/public/js/CKEditor/embed/content/embed-ui.js
> +            languageCodes: items[0].ContentInfo.Content.CurrentVersion.Version.VersionInfo.VersionTranslationInfo.Language.map(
same as above

2023-09-06 10:09 UTC, Gengar-i approved these changes

2023-09-07 12:46 UTC, GrabowskiM approved these changes

2023-09-08 07:10 UTC, dew326 approved these changes

2023-10-19 07:27 UTC, micszo approved these changes

2023-10-19 07:34 UTC, merged