IBX-6843: Focus mode
ibexa/fieldtype-richtext pull request #133
Opened 2023-10-24 12:49 UTC by lucasOsti

Draft

2023-10-30 14:18 UTC, GrabowskiM requested changes

2023-10-30 14:18 UTC, GrabowskiM commented on src/bundle/Resources/public/js/CKEditor/core/base-ckeditor.js
> +                    const { top: dataSourceTop } = dataSourceNodeRect;
I don't think these two extra variables are necessary here
```suggestion
                    const { height: toolbarHeight } = toolbarNode.getBoundingClientRect();
                    const { top: dataSourceTop } = dataSourceNode.getBoundingClientRect();
```

2023-10-31 12:57 UTC, Gengar-i approved these changes

2023-11-03 09:59 UTC, GrabowskiM approved these changes

2023-11-06 14:07 UTC, dew326 approved these changes

2023-11-17 11:44 UTC, micszo approved these changes

2023-11-17 11:50 UTC, merged