IBX-6889: Added custom attributes to links
ibexa/fieldtype-richtext pull request #134
Opened 2023-11-14 13:28 UTC by dew326

| Question           | Answer
| ------------------ | ------------------
| **JIRA issue**     | https://issues.ibexa.co/browse/IBX-6889
| **Bug/Improvement**| no
| **New feature**    | yes
| **Target version** | main
| **BC breaks**      | no
| **Tests pass**     | yes
| **Doc needed**     | no

**TODO**:
- [x] Implement feature / fix a bug.
- [x] Implement tests.
- [x] Fix new code according to Coding Standards (`$ composer fix-cs`).
- [x] Ask for Code Review.

2023-11-17 09:29 UTC, GrabowskiM requested changes

2023-11-17 09:29 UTC, GrabowskiM commented on src/bundle/Resources/public/js/CKEditor/link/ui/link-form-view.js
> +                children: ['Custom Attributes'],
Translation?

2023-11-17 09:29 UTC, GrabowskiM commented on src/bundle/Resources/public/js/CKEditor/link/ui/link-form-view.js
> +        const customAttributesDefinitions = [];
```suggestion
        const customClassesLinkConfig = customClassesConfig.link;
        const customAttributesDefinitions = [];

        this.children = this.createFormChildren();
        this.attributesChildren = this.createFromAttributesChildren(customAttributesLinkConfig, customClassesLinkConfig);
```

2023-11-17 09:29 UTC, GrabowskiM commented on src/bundle/Resources/public/js/CKEditor/link/ui/link-form-view.js
> +
I think that's unneded new line?

2023-11-17 11:20 UTC, lucasOsti approved these changes

2023-11-17 14:56 UTC, GrabowskiM approved these changes

2023-11-20 09:55 UTC, tischsoic approved these changes

2023-11-20 13:27 UTC, merged