IBX-7503: Fixed custom attributes
ibexa/fieldtype-richtext pull request #152
Opened 2024-03-11 11:28 UTC by dew326

| Question           | Answer
| ------------------ | ------------------
| **JIRA issue**     | https://issues.ibexa.co/browse/IBX-7503
| **Bug/Improvement**| yes
| **New feature**    | no
| **Target version** | 4.5
| **BC breaks**      | no
| **Tests pass**     | yes
| **Doc needed**     | no

**TODO**:
- [x] Implement feature / fix a bug.
- [x] Implement tests.
- [x] Fix new code according to Coding Standards (`$ composer fix-cs`).
- [x] Ask for Code Review.

2024-03-11 12:15 UTC, Gengar-i requested changes

2024-03-11 12:15 UTC, Gengar-i commented on src/bundle/Resources/public/js/CKEditor/custom-attributes/custom-attributes-editing.js
> +const configElementsMapping = {
```suggestion
export const configElementsMapping = {
```

2024-03-11 12:15 UTC, Gengar-i commented on src/bundle/Resources/public/js/CKEditor/custom-attributes/custom-attributes-editing.js
> +export { configElementsMapping };
```suggestion
```

2024-03-11 12:15 UTC, Gengar-i commented on src/bundle/Resources/public/js/CKEditor/custom-attributes/custom-attributes-editing.js
> +const configElementsMapping = {
What do you think?

2024-03-11 12:15 UTC, Gengar-i commented on src/bundle/Resources/public/js/CKEditor/custom-attributes/custom-attributes-editing.js
>  export default IbexaCustomAttributesEditing;
```suggestion
export { default as IbexaCustomAttributesEditing, configElementsMapping };
```

2024-03-11 12:15 UTC, Gengar-i commented on src/bundle/Resources/public/js/CKEditor/custom-attributes/custom-attributes-editing.js
>  export default IbexaCustomAttributesEditing;
Or like this

2024-03-12 09:20 UTC, GrabowskiM requested changes

2024-03-12 09:20 UTC, GrabowskiM commented on src/bundle/Resources/public/js/CKEditor/custom-attributes/helpers/config-helper.js
> +    return configName ? configName[0] : elementName;
```suggestion
    return configName?.[0] ?? elementName;
```
?

2024-03-12 09:20 UTC, GrabowskiM commented on src/bundle/Resources/public/js/CKEditor/plugins/elements-path.js
> +                }
```suggestion
                this.isTableCellSelected = element.name === 'tableCell';
                
                const placement = this.isTableCellSelected ? 'on' : 'in';
```

2024-03-12 09:29 UTC, lucasOsti approved these changes

2024-03-12 09:43 UTC, GrabowskiM approved these changes

2024-03-12 09:47 UTC, Gengar-i approved these changes

2024-03-19 14:23 UTC, merged