IBX-9016: Tags: Facebook and X are not visible in Text block in Page builder
ibexa/fieldtype-richtext pull request #189
Opened 2024-10-10 13:15 UTC by GrabowskiM

| :ticket: Issue | [IBX-9016](https://issues.ibexa.co/browse/IBX-9016) |
|----------------|-----------|

#### Description:

#### For QA:

#### Documentation:

2024-10-11 07:19 UTC, bozatko approved these changes

2024-10-11 10:35 UTC, dew326 approved these changes

2024-10-17 10:35 UTC, lucasOsti approved these changes

2024-10-22 08:22 UTC, barbaragr requested changes
**Steps:**
1. Go to creating LP
2. Fill required fields
3. Drag and drop text lock
4. Paste some text (Lorem ipsum for example)
5. Place X tag in text (I used: https://x.com/memes/status/854385007116210177)
6. Place FB tag in text (I used: https://www.facebook.com/photo?fbid=3601559816533791&set=a.462771523745985)
7. Confirm

**Actual result:** 
Tags are still not visible in block.

8. Click Publish
9. Go to edit mode

**Actual result:**
Both tags are visible. It happened twice that X was doubled.

https://github.com/user-attachments/assets/4271b221-ef2f-4b46-9064-4590f7837028



10. Click Publish again
11. Go to Preview

**Actual result:**
X is visible in preview, but FB is not.

2024-12-05 10:40 UTC, closed without merging