IBX-9154: The dropdown for custom class is illegible
ibexa/fieldtype-richtext pull request #193
Opened 2024-11-18 10:31 UTC by lucasOsti

| :ticket: Issue | IBX-9154 |
|----------------|-----------|

#### Description:

#### For QA:

#### Documentation:

2024-11-18 14:31 UTC, adamwojs approved these changes

2024-11-19 07:09 UTC, dew326 approved these changes

2024-11-19 08:24 UTC, bozatko approved these changes

2024-11-20 10:15 UTC, GrabowskiM approved these changes

2024-11-20 14:13 UTC, tischsoic approved these changes

2024-11-25 14:32 UTC, GrabowskiM approved these changes

2024-11-25 14:32 UTC, GrabowskiM commented on src/bundle/Resources/public/js/CKEditor/custom-attributes/custom-attributes-ui.js
> +        let timeoutId = null;
i think new line? Or not, I'm already totally lost :D

2024-11-26 10:33 UTC, dew326 approved these changes

2024-11-26 11:21 UTC, bozatko approved these changes

2024-11-28 08:52 UTC, KamilSznajdrowicz requested changes
After applying the patch to version 4.6.13 in bundle fieldtype-richtext, an error occurs when running the yarn encore dev command:
![Zrzut ekranu 2024-11-28 o 09 46 06](https://github.com/user-attachments/assets/a268e066-cca8-4cf0-a43b-7e42e83b6bdb)

When opening any article, I cannot type anything into the intro and body fields, and errors appear in the console:
![Zrzut ekranu 2024-11-28 o 09 49 08](https://github.com/user-attachments/assets/7df64dfc-af48-467b-9518-a7c5e021cca5)

2024-12-05 13:09 UTC, KamilSznajdrowicz approved these changes
QA Approve
PR tested on 4.6.x-dev, patch applied (with GNU version) and successfully tested on v4.6.14

2024-12-05 13:26 UTC, merged