IBX-9296: Custom CSS classes not working for "embedimage"
ibexa/fieldtype-richtext pull request #197
Opened 2024-12-09 12:11 UTC by GrabowskiM

| :ticket: Issue | [IBX-9296](https://issues.ibexa.co/browse/IBX-9296) |
|----------------|-----------|

#### Description:
Custom class was there under `custom-classes` attribute, but it was in form of `ibexa-embed-type-image {custom_class}` so `cleanClasses` method was removing this whole attribute (as `ibexa-embed-type-image` wasn't in custom classes options config and all custom-classes had to be matched)

I've added to config info about this component class and before any checks I remove it from attribute.
Also, I have to remove it later manually from attributes, as otherwise `ibexa-embed-type-image` is duplicated - probably comes from container declaration and from custom-classes, co one of these origins had to be cleared.

#### For QA:

#### Documentation:

2024-12-10 07:11 UTC, dew326 approved these changes

2024-12-11 08:47 UTC, lucasOsti approved these changes

2024-12-13 07:26 UTC, bozatko approved these changes

2024-12-13 12:44 UTC, tischsoic approved these changes

2024-12-17 12:49 UTC, barbaragr commented
I have noticed differences in display for testing on PR vs testing with patch as below:

- for PR:
<img width="490" alt="Screenshot 2024-12-17 at 13 47 05" src="https://github.com/user-attachments/assets/f7f7c2ec-d15d-4877-a0d3-b9dcbb6ef0d7" />

- for patch:
<img width="421" alt="Screenshot 2024-12-17 at 13 49 11" src="https://github.com/user-attachments/assets/fa72b1ac-8afc-4f4e-a586-deca477760e4" />

2024-12-18 10:47 UTC, barbaragr requested changes
I've put an issue in comment above.

2025-01-09 08:56 UTC, barbaragr approved these changes

2025-01-09 09:10 UTC, merged