IBX-9297: Custom CSS can not be removed from link element
ibexa/fieldtype-richtext pull request #199
Opened 2024-12-11 17:05 UTC by GrabowskiM

| :ticket: Issue | IBX-XXXXX |
|----------------|-----------|

#### Description:

#### For QA:

#### Documentation:

2024-12-12 13:38 UTC, lucasOsti approved these changes

2024-12-12 14:03 UTC, dew326 approved these changes

2024-12-13 11:41 UTC, bozatko approved these changes

2024-12-18 10:46 UTC, barbaragr requested changes
1. If I click "Remove attributes" button, it clears every field in link pop up, not only Custom attributes field. And if I publish and then go again to edit mode, everything is still visible. 
2. I've noticed that Remove link button removes only field value, in richtext link still exists and if user click Publish button, receives Bad request, "Argument '$xmlDoc' is invalid: Transformation of XML content failed: Error in 0:0: Unhandled link type". Should I report it as follow up? **Update:** reported in https://issues.ibexa.co/browse/IBX-9366

2025-01-08 10:43 UTC, bozatko approved these changes

2025-01-08 12:30 UTC, lucasOsti approved these changes

2025-01-08 13:24 UTC, barbaragr requested changes
1. I can select all the options by clicking them. Should it be possible? In this case: https://issues.ibexa.co/browse/IBX-9298 it is set for multiple and checkboxes are displayed.
<img width="499" alt="Screenshot 2025-01-08 at 14 14 50" src="https://github.com/user-attachments/assets/f423ebb7-38d7-4fec-ab76-62448d9c8d69" />

2. If I select anything in custom attributes and fill for example Title field and then go out without saving: all the fields are cleared except Custom attributes.
<img width="460" alt="Screenshot 2025-01-08 at 14 24 25" src="https://github.com/user-attachments/assets/562d29c2-182b-4f01-ad4c-ffb1758060ee" />

2025-01-16 09:22 UTC, barbaragr approved these changes

2025-01-17 06:58 UTC, dew326 approved these changes

2025-01-17 06:58 UTC, merged