IBX-9298: multiple Custom CSS - no visual indication of selected items
ibexa/fieldtype-richtext pull request #200
Opened 2024-12-12 15:53 UTC by GrabowskiM

| :ticket: Issue | [IBX-9298](https://issues.ibexa.co/browse/IBX-9298) |
|----------------|-----------|

#### Description:

#### For QA:

#### Documentation:

2024-12-16 09:52 UTC, lucasOsti approved these changes

2024-12-16 09:52 UTC, lucasOsti commented on src/bundle/Resources/public/scss/_balloon-form.scss
> +                            font-size: calculateRem(12px);
```suggestion
                            font-size: $ibexa-text-font-size-small;
```

2024-12-17 10:32 UTC, dew326 approved these changes

2024-12-17 10:41 UTC, bozatko approved these changes

2024-12-17 10:41 UTC, bozatko commented on src/bundle/Resources/public/scss/_balloon-form.scss
> +                                    box-shadow: 0 0 0 calculateRem(4px) rgba($ibexa-color-primary, 0.25);
this will be the third use of such box-shadow i the project. What do you think about creating new shadow variable?

2025-01-08 12:18 UTC, barbaragr requested changes
When I select any option I need to click Save twice to close the pop up, because for the first time just the menu is closed. Changes are not saved. See attachment, please.

https://github.com/user-attachments/assets/69290380-8881-47e3-95c4-b0d58dac8276

2025-01-09 09:21 UTC, barbaragr commented
To future me:
Please retest also this one:
https://github.com/user-attachments/assets/0f302093-ad4f-4245-bbf0-8ea9cf15d4c4
(config from: https://issues.ibexa.co/browse/IBX-9296)
Thanks!

2025-01-29 13:32 UTC, GrabowskiM commented
> Several issues to decide if they should be fixed in this PR or reported as follow up:
> 
>  css_01.mov 
> 1. Too narrow checkboxes (visible when checked)
> 2. If I select couple of options, it's displayed as "option1 +number". After saving all the selected options are displayed. If I change anything it comes back to the format with number.
> 3. I need to click Save button twice to close the whole popup
> 
> https://github.com/user-attachments/assets/9b88801d-20c7-4e0e-8cd8-1870f2477ad8 4. If I change something, but didn't save, just clicked outside the popup, it will not get closed. Even if i click other buttons, like anchor it always go back to custom attributes popup.

Fixed 1 and 2, 3 and 4 I would create new tickets, as it's not directly connected to dropdown and it's already like this on 4.6

2025-02-14 14:03 UTC, barbaragr approved these changes
1, 2 - done
3, 4 - I will report it as follow up: https://issues.ibexa.co/browse/IBX-9583 https://issues.ibexa.co/browse/IBX-9582

2025-02-14 16:34 UTC, merged