IBX-2677: As a developer I want to have prettier and eslint style check/fix
ibexa/fieldtype-richtext pull request #38
Opened 2022-04-11 11:16 UTC by GrabowskiM

JIRA ref: https://issues.ibexa.co/browse/IBX-2677

Set version for eslint-ibexa-config and fix prettier issues

2022-04-25 07:21 UTC, lucasOsti approved these changes

2022-04-27 09:19 UTC, tischsoic approved these changes

2022-04-27 10:12 UTC, dew326 requested changes

2022-04-27 10:12 UTC, dew326 commented on src/bundle/Resources/public/js/CKEditor/embed/image/embed-image-editing.js
> +                        'size',
please look the comment

2022-04-27 10:19 UTC, dew326 approved these changes

2022-05-02 08:30 UTC, merged