test customAttributes
ibexa/fieldtype-richtext pull request #42
Opened 2022-05-03 21:14 UTC by wizhippo

| Question           | Answer
| ------------------ | ------------------
| **JIRA issue**     | [EZP-32439](https://issues.ibexa.co/browse/EZP-32439)
| **Bug**| yes
| **New feature**    | no
| **Target version** | 4,0
| **BC breaks**      | no
| **Tests pass**     | yes/no
| **Doc needed**     | no

Check if customAttributes exist and are an array before trying to iterate.

**TODO**:
- [ ] Implement feature / fix a bug.
- [ ] Implement tests.
- [ ] Fix new code according to Coding Standards (`$ composer fix-cs`).
- [ ] Ask for Code Review.

2022-05-10 05:25 UTC, dew326 reviewed
Hi @wizhippo, thanks for the contribution.

This bug is in 4.1 as well, so the target branch should be 4.1. Please change it and rebase your branch.

2022-05-10 05:25 UTC, dew326 commented on src/bundle/Resources/public/js/CKEditor/custom-attributes/ui/custom-attributes-form-view.js
> +        if (customAttributes && Object.keys(customAttributes).length !== 0) {
```suggestion
        if (customAttributes) {
```
I think this check is enough

2022-05-11 05:38 UTC, dew326 approved these changes

2022-05-11 07:30 UTC, GrabowskiM approved these changes

2022-05-11 12:01 UTC, lucasOsti approved these changes

2022-05-11 12:05 UTC, tischsoic approved these changes

2022-05-12 09:41 UTC, katarzynazawada requested changes
Unfortunately, I tested this fix and issue still occurs.
![Zrzut ekranu 2022-05-12 o 10 51 49](https://user-images.githubusercontent.com/42930265/168041133-0ec3253e-8704-44df-b5e0-ae1442b6a66f.png)

I added following configuration 
```
ibexa:
    system:
        default:
            fieldtypes:
                ezrichtext:
                    custom_tags: [ezfactbox]
                    toolbar:
                        custom_tags_group:
                            buttons:
                                ezfactbox:
                                    priority: 5
ibexa_fieldtype_richtext:
     custom_tags:
        ezfactbox:
            template: field_type/ibexa_fieldtype_richtext/custom_tags/ezfactbox.html.twig
            icon: '/assets/field_type/ibexa_fieldtype_richtext/custom_tags/icon/factbox.svg#factbox'```

2022-05-27 20:28 UTC, wizhippo commented
Found additional location where check is needed,

2022-05-27 20:29 UTC, wizhippo commented
Found additional location where check is needed

2022-05-30 06:24 UTC, dew326 approved these changes

2022-05-31 09:38 UTC, katarzynazawada approved these changes

2022-05-31 09:41 UTC, merged

2023-01-08 23:55 UTC, davidsayre commented
I'm using DXP 4.3 and this bug is appearing.
I have a simple 'separator' and this creates a richtext editor when inserted in

ibexa_fieldtype_richtext:
        separator:
            template: '@standard/ezrichtext/custom_tags/separator.html.twig'
            icon: '/bundles/ibexaicons/img/all-icons.svg#interface-block'
            # ezcontent field is implied / has no attributes

2023-01-19 17:40 UTC, fsoedjede commented
Hello @wizhippo,

I'm using DXP 4.3 and I have a bug when I don't define attributes. Same case as @davidsayre .

After investigating, I found that the problem can be fixed at two places:

1. In PHP class

Add empty attributes item in the array
https://github.com/ibexa/fieldtype-richtext/blob/main/src/lib/Configuration/UI/Mapper/CustomTag.php#L95-L99
```diff
            $config[$tagName] = [
                'label' => "ezrichtext.custom_tags.{$tagName}.label",
                'description' => "ezrichtext.custom_tags.{$tagName}.description",
                'isInline' => $customTagConfiguration['is_inline'],
+               'attributes' => [],
            ];
```

*It's the solution I applied in my use case*

2. In JS files

- https://github.com/ibexa/fieldtype-richtext/blob/main/src/bundle/Resources/public/js/CKEditor/custom-tags/block-custom-tag/custom-tag-ui.js#L173-L177 **AND** https://github.com/ibexa/fieldtype-richtext/blob/main/src/bundle/Resources/public/js/CKEditor/custom-tags/inline-custom-tag/inline-custom-tag-ui.js#L115-L119
```diff
-        const values = Object.entries(this.config.attributes).reduce((outputValues, [attributeName, config]) => {
-            outputValues[attributeName] = config.defaultValue;
-
-            return outputValues;
-        }, {});
+        let values = {};
+        if (this.config.attributes !== undefined) {
+            values = Object.entries(this.config.attributes).reduce((outputValues, [attributeName, config]) => {
+                outputValues[attributeName] = config.defaultValue;
+
+                return outputValues;
+            }, {});
+        }
```

Explanation:

As `attributes` is not provided in some case, the error occures because some parts of JS assume that there is always attributes.

The suggested changes are an attempt to fix the issues I saw.

Can I open a PR for that?

2023-01-19 18:51 UTC, wizhippo commented
@fsoedjede Of course you can open PR for this.  Glad you found a solution.