IBX-3973: Nontranslatable and disabled fields are not greyed out in c…
ibexa/fieldtype-richtext pull request #57
Opened 2022-10-19 13:58 UTC by GrabowskiM

…ontent editing UI

| Question           | Answer
| ------------------ | ------------------
| **JIRA issue**     | [IBX-XXXXX](https://issues.ibexa.co/browse/IBX-XXXXX)
| **Bug/Improvement**| yes/no
| **New feature**    | yes/no
| **Target version** | latest stable for bug fixes, `main` for new features
| **BC breaks**      | yes/no
| **Tests pass**     | yes/no
| **Doc needed**     | yes/no

**TODO**:
- [ ] Implement feature / fix a bug.
- [ ] Implement tests.
- [ ] Fix new code according to Coding Standards (`$ composer fix-cs`).
- [ ] Ask for Code Review.

2022-10-21 11:53 UTC, dew326 approved these changes

2022-10-24 09:39 UTC, lucasOsti approved these changes

2022-10-27 16:15 UTC, tischsoic approved these changes

2022-11-16 13:13 UTC, Gengar-i requested changes

2022-11-16 13:13 UTC, Gengar-i commented on src/bundle/Resources/public/scss/variables/colors.scss
>  $ibexa-color-light-300: #f3f3f6 !default;
There suppose to be 200?

2022-11-17 10:48 UTC, Gengar-i approved these changes

2022-11-18 08:26 UTC, katarzynazawada approved these changes

2022-11-18 09:35 UTC, merged