IBX-5147: [Rich text field type] Closing custom tag before finishing edition causes edition to hover.
ibexa/fieldtype-richtext pull request #75
Opened 2023-02-27 13:07 UTC by GrabowskiM

| Question           | Answer
| ------------------ | ------------------
| **JIRA issue**     | https://issues.ibexa.co/browse/IBX-5147
| **Bug/Improvement**| yes
| **New feature**    | no
| **Target version** | 4.3
| **BC breaks**      | no
| **Tests pass**     | yes
| **Doc needed**     | no

**TODO**:
- [x] Implement feature / fix a bug.
- [ ] Implement tests.
- [x] Fix new code according to Coding Standards (`$ composer fix-cs`).
- [x] Ask for Code Review.

2023-02-27 13:45 UTC, dew326 requested changes

2023-02-27 13:45 UTC, dew326 commented on src/bundle/Resources/public/js/CKEditor/custom-tags/block-custom-tag/custom-tag-ui.js
> +                this.hideAttributes();
shouldn't we hideAttributes before the element is removed?

2023-02-28 14:32 UTC, Gengar-i approved these changes

2023-03-03 10:12 UTC, lucasOsti approved these changes

2023-03-03 10:12 UTC, dew326 approved these changes

2023-03-06 09:57 UTC, jwibexa approved these changes
Tested and validated
Ibexa Experience Version 4.3.4
Chrome and FF

2023-03-06 11:25 UTC, merged