IBX-2349/5244/5245: Added possibility to add link into embed image
ibexa/fieldtype-richtext pull request #78
Opened 2023-03-17 10:18 UTC by dew326

| Question           | Answer
| ------------------ | ------------------
| **JIRA issue**     | https://issues.ibexa.co/browse/IBX-2349 https://issues.ibexa.co/browse/IBX-5245 https://issues.ibexa.co/browse/IBX-5325
| **Bug**| yes
| **New feature**    |o
| **Target version** | 4.4
| **BC breaks**      | no
| **Tests pass**     | yes
| **Doc needed**     | no

**TODO**:
- [x] Implement feature / fix a bug.
- [x] Implement tests.
- [x] Fix new code according to Coding Standards (`$ composer fix-cs`).
- [x] Ask for Code Review.

2023-03-17 12:58 UTC, GrabowskiM requested changes

2023-03-17 14:07 UTC, GrabowskiM approved these changes

2023-03-20 18:16 UTC, lucasOsti approved these changes

2023-03-21 13:26 UTC, GrabowskiM approved these changes

2023-03-21 13:31 UTC, Gengar-i approved these changes

2023-03-21 13:51 UTC, lucasOsti approved these changes

2023-03-21 14:19 UTC, tischsoic approved these changes

2023-03-23 10:30 UTC, jwibexa approved these changes
Manually tested Tested and validated on 4.5 experience FF and chrome

2023-03-23 12:16 UTC, merged