IBX-5715: Added validate if anchor value is unique and valid
ibexa/fieldtype-richtext pull request #94
Opened 2023-06-21 07:27 UTC by mateuszdebinski

| Question           | Answer
| ------------------ | ------------------
| **JIRA issue**     | [IBX-5715](https://issues.ibexa.co/browse/IBX-5715)
| **Bug/Improvement**| yes
| **New feature**    | no
| **Target version** | 4.5
| **BC breaks**      | no
| **Tests pass**     | yes
| **Doc needed**     | no

I had no other idea to verify if an element is unique, the previous solution doesn't work anymore. I'd love to hear other ideas for checking the uniqueness of the ID

**TODO**:
- [x] Implement feature / fix a bug.
- [ ] Implement tests.
- [ ] Fix new code according to Coding Standards (`$ composer fix-cs`).
- [x] Ask for Code Review.

2023-06-22 10:30 UTC, dew326 approved these changes

2023-06-26 07:20 UTC, lucasOsti approved these changes

2023-06-27 08:26 UTC, Gengar-i approved these changes

2023-06-29 08:40 UTC, GrabowskiM requested changes

2023-06-29 08:40 UTC, GrabowskiM commented on src/bundle/Resources/public/js/CKEditor/anchor/anchor-ui.js
> +            return true;
```suggestion
            countElementsWithSameId += richtext.querySelectorAll(`[id="${value}"]`).length;

            return countElementsWithSameId > 1;
```

2023-07-03 09:49 UTC, GrabowskiM approved these changes

2023-07-04 10:58 UTC, micszo commented
@mateuszdebinski what's the decision regarding CI state?

2023-07-04 11:37 UTC, mateuszdebinski commented
@micszo I did a rebase, and now it's ok

2023-07-04 12:13 UTC, micszo reviewed
Following error occurs when clicking Save:

![Screenshot 2023-07-04 at 13 34 57](https://github.com/ibexa/fieldtype-richtext/assets/13622502/410fff68-ee02-456d-a7cc-a744ca6438af)

2023-07-05 12:14 UTC, micszo approved these changes
QA Approved on Ibexa Experience 4.5.1-dev.

2023-07-05 12:18 UTC, merged