IBX-5981: Fixed handling multiple custom classes
ibexa/fieldtype-richtext pull request #95
Opened 2023-06-22 10:52 UTC by dew326

| Question           | Answer
| ------------------ | ------------------
| **JIRA issue**     | https://issues.ibexa.co/browse/IBX-5981
| **Bug/Improvement**| yes
| **New feature**    | no
| **Target version** | 4.5
| **BC breaks**      | no
| **Tests pass**     | yes
| **Doc needed**     | no

**TODO**:
- [x] Implement feature / fix a bug.
- [x] Implement tests.
- [x] Fix new code according to Coding Standards (`$ composer fix-cs`).
- [x] Ask for Code Review.

2023-06-22 10:53 UTC, Gengar-i approved these changes

2023-06-22 10:55 UTC, lucasOsti approved these changes

2023-06-22 11:01 UTC, GrabowskiM approved these changes

2023-06-22 11:09 UTC, tischsoic approved these changes

2023-06-22 11:09 UTC, tischsoic commented on src/bundle/Resources/public/js/CKEditor/custom-attributes/ui/custom-attributes-form-view.js
> +            const alreadySelectedValues = labeledDropdown.fieldView.element.value ? labeledDropdown.fieldView.element.value.split(',') : [];
maybe we can use optional chaining?
```suggestion
            const alreadySelectedValues = labeledDropdown.fieldView.element.value.split?.(',') ?? [];
```

2023-06-22 13:39 UTC, micszo reviewed
There is a visual issue without default value before choosing first value.

![Screenshot 2023-06-22 at 15 34 12](https://github.com/ibexa/fieldtype-richtext/assets/13622502/e7cde52c-d054-482e-a4ae-3ad474ea43e3)

2023-06-22 13:51 UTC, micszo commented
When using following config 
```
                        paragraph:
                            choices: [ regular, special, tip_box, warning_box ]
#                            default_value: regular
                            required: false
                            multiple: false
                        heading:
                            choices: [ foo, bar ]
#                            default_value: foo
                            required: false
                            multiple: true
                        heading2:
                            choices: [ titre1, titre2, titre3 ]
#                            default_value: titre1
                            required: true
                            multiple: false
                        heading3:
                            choices: [ test1, test2, test3 ]
#                            default_value: test1
                            required: true
                            multiple: true
```

values are being carried over between classes:

![Screenshot 2023-06-22 at 15 48 21](https://github.com/ibexa/fieldtype-richtext/assets/13622502/4d0b061f-e817-4939-b31d-510c04f6f0fd)

2023-06-22 13:58 UTC, micszo commented
Console error occurs when saving custom attributes:

![Screenshot 2023-06-22 at 15 41 18](https://github.com/ibexa/fieldtype-richtext/assets/13622502/05901a3e-87d6-4976-9090-7ff016204d83)

2023-06-22 14:02 UTC, micszo requested changes
Please see comments above.

2023-06-23 06:16 UTC, micszo commented
Additional feedback from customer: https://jsd.ez.no/browse/CS-11138?focusedCommentId=276759&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-276759

2023-06-28 12:15 UTC, dew326 commented
@micszo all issues should be fixed. Please note there is another PR https://github.com/ibexa/admin-ui/pull/828

2023-06-29 14:00 UTC, micszo approved these changes
Thanks for fixing all the issues!

QA Approved on Ibexa Experience 4.5.1-dev.

2023-06-29 14:11 UTC, merged