IBX-6026: Fixed deleting multiple custom tags in once
ibexa/fieldtype-richtext pull request #99
Opened 2023-07-04 07:13 UTC by dew326

| Question           | Answer
| ------------------ | ------------------
| **JIRA issue**     | https://issues.ibexa.co/browse/IBX-6026
| **Bug/Improvement**| yes
| **New feature**    | no
| **Target version** | 4.5
| **BC breaks**      | no
| **Tests pass**     | yes
| **Doc needed**     | no

**TODO**:
- [x] Implement feature / fix a bug.
- [x] Implement tests.
- [x] Fix new code according to Coding Standards (`$ composer fix-cs`).
- [x] Ask for Code Review.

2023-07-04 13:05 UTC, lucasOsti approved these changes

2023-07-04 13:05 UTC, tischsoic approved these changes

2023-07-04 13:09 UTC, GrabowskiM requested changes

2023-07-04 13:09 UTC, GrabowskiM commented on src/bundle/Resources/public/js/CKEditor/custom-tags/block-custom-tag/custom-tag-ui.js
> +            modelElement.getAttribute('customTagName') === this.componentName
```suggestion
            modelElement?.name === 'customTag' &&
            modelElement?.getAttribute('customTagName') === this.componentName
```

2023-07-06 08:04 UTC, GrabowskiM approved these changes

2023-07-11 08:43 UTC, tomaszszopinski approved these changes
QA approved on IbexaDXP 4.5 commerce.

2023-07-11 08:45 UTC, merged